//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAAG
{
    using System;
    using System.Collections.Generic;
    
    public partial class Analisis
    {
        public Analisis()
        {
            this.Analisis_Dato = new HashSet<Analisis_Dato>();
            this.Muestra_Analisis = new HashSet<Muestra_Analisis>();
        }
    
        public int IdAnalisis { get; set; }
        public string Nombre { get; set; }
        public int IdCategoria { get; set; }
        public decimal Costo { get; set; }
        public string Descripcion { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual ICollection<Analisis_Dato> Analisis_Dato { get; set; }
        public virtual ICollection<Muestra_Analisis> Muestra_Analisis { get; set; }
    }
}
