//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAAG
{
    using System;
    using System.Collections.Generic;
    
    public partial class Canton
    {
        public Canton()
        {
            this.Distrito = new HashSet<Distrito>();
        }
    
        public int ID_Canton { get; set; }
        public int ID_Provincia { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<Distrito> Distrito { get; set; }
        public virtual Provincia Provincia { get; set; }
    }
}
