//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAAG
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categoria
    {
        public Categoria()
        {
            this.Analisis = new HashSet<Analisis>();
            this.Analisis1 = new HashSet<Analisis>();
        }
    
        public int IdCategoria { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<Analisis> Analisis { get; set; }
        public virtual ICollection<Analisis> Analisis1 { get; set; }
    }
}
