//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAAG
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categoria
    {
        public Categoria()
        {
            this.Analisis = new HashSet<Analisis>();
        }
    
        public int IdCategoria { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<Analisis> Analisis { get; set; }
    }
}
