#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAAG
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AGRONOMICOSDB")]
	public partial class DataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertAnalisis(Analisis instance);
    partial void UpdateAnalisis(Analisis instance);
    partial void DeleteAnalisis(Analisis instance);
    partial void InsertTelefono(Telefono instance);
    partial void UpdateTelefono(Telefono instance);
    partial void DeleteTelefono(Telefono instance);
    partial void InsertFactura(Factura instance);
    partial void UpdateFactura(Factura instance);
    partial void DeleteFactura(Factura instance);
    partial void InsertMuestra(Muestra instance);
    partial void UpdateMuestra(Muestra instance);
    partial void DeleteMuestra(Muestra instance);
    partial void InsertMuestra_analisis(Muestra_analisis instance);
    partial void UpdateMuestra_analisis(Muestra_analisis instance);
    partial void DeleteMuestra_analisis(Muestra_analisis instance);
    partial void InsertPersona(Persona instance);
    partial void UpdatePersona(Persona instance);
    partial void DeletePersona(Persona instance);
    partial void InsertReporte(Reporte instance);
    partial void UpdateReporte(Reporte instance);
    partial void DeleteReporte(Reporte instance);
    partial void InsertResultado_analisis(Resultado_analisis instance);
    partial void UpdateResultado_analisis(Resultado_analisis instance);
    partial void DeleteResultado_analisis(Resultado_analisis instance);
    partial void InsertResultado_elemento(Resultado_elemento instance);
    partial void UpdateResultado_elemento(Resultado_elemento instance);
    partial void DeleteResultado_elemento(Resultado_elemento instance);
    #endregion

   
        public IQueryable<Persona> IsValidUser(string userName, string passWord)
        {
            DataDataContext myDB = new DataDataContext();

            var userResults = from u in myDB.Persona
                              where u.NombreUsuario == userName
                              && u.Clave == passWord && u.Estado==0
                              select u;
            return userResults;
        }

       /* public int[] getId_Tipo() { 
            var userResults = from u in myDB.Persona
                              where u.nom
        }*/

		public DataDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["AGRONOMICOSDBConnectionString2"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Analisis> Analisis
		{
			get
			{
				return this.GetTable<Analisis>();
			}
		}
		
		public System.Data.Linq.Table<Telefono> Telefono
		{
			get
			{
				return this.GetTable<Telefono>();
			}
		}
		
		public System.Data.Linq.Table<Factura> Factura
		{
			get
			{
				return this.GetTable<Factura>();
			}
		}
		
		public System.Data.Linq.Table<Muestra> Muestra
		{
			get
			{
				return this.GetTable<Muestra>();
			}
		}
		
		public System.Data.Linq.Table<Muestra_analisis> Muestra_analisis
		{
			get
			{
				return this.GetTable<Muestra_analisis>();
			}
		}
		
		public System.Data.Linq.Table<Persona> Persona
		{
			get
			{
				return this.GetTable<Persona>();
			}
		}
		
		public System.Data.Linq.Table<Reporte> Reporte
		{
			get
			{
				return this.GetTable<Reporte>();
			}
		}
		
		public System.Data.Linq.Table<Resultado_analisis> Resultado_analisis
		{
			get
			{
				return this.GetTable<Resultado_analisis>();
			}
		}
		
		public System.Data.Linq.Table<Resultado_elemento> Resultado_elemento
		{
			get
			{
				return this.GetTable<Resultado_elemento>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Analisis")]
	public partial class Analisis : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdAnalisis;
		
		private string _Nombre;
		
		private string _Categoria;
		
		private string _Descripcion;
		
		private string _UsuarioCreacion;
		
		private System.DateTime _FechaCreacion;
		
		private string _UsuarioActualizacion;
		
		private System.Nullable<System.DateTime> _FechaActualizacion;
		
		private EntitySet<Muestra_analisis> _Muestra_analisis;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdAnalisisChanging(int value);
    partial void OnIdAnalisisChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnCategoriaChanging(string value);
    partial void OnCategoriaChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnUsuarioCreacionChanging(string value);
    partial void OnUsuarioCreacionChanged();
    partial void OnFechaCreacionChanging(System.DateTime value);
    partial void OnFechaCreacionChanged();
    partial void OnUsuarioActualizacionChanging(string value);
    partial void OnUsuarioActualizacionChanged();
    partial void OnFechaActualizacionChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaActualizacionChanged();
    #endregion
		
		public Analisis()
		{
			this._Muestra_analisis = new EntitySet<Muestra_analisis>(new Action<Muestra_analisis>(this.attach_Muestra_analisis), new Action<Muestra_analisis>(this.detach_Muestra_analisis));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAnalisis", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdAnalisis
		{
			get
			{
				return this._IdAnalisis;
			}
			set
			{
				if ((this._IdAnalisis != value))
				{
					this.OnIdAnalisisChanging(value);
					this.SendPropertyChanging();
					this._IdAnalisis = value;
					this.SendPropertyChanged("IdAnalisis");
					this.OnIdAnalisisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Categoria", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Categoria
		{
			get
			{
				return this._Categoria;
			}
			set
			{
				if ((this._Categoria != value))
				{
					this.OnCategoriaChanging(value);
					this.SendPropertyChanging();
					this._Categoria = value;
					this.SendPropertyChanged("Categoria");
					this.OnCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(50)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioCreacion", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string UsuarioCreacion
		{
			get
			{
				return this._UsuarioCreacion;
			}
			set
			{
				if ((this._UsuarioCreacion != value))
				{
					this.OnUsuarioCreacionChanging(value);
					this.SendPropertyChanging();
					this._UsuarioCreacion = value;
					this.SendPropertyChanged("UsuarioCreacion");
					this.OnUsuarioCreacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCreacion", DbType="Date NOT NULL")]
		public System.DateTime FechaCreacion
		{
			get
			{
				return this._FechaCreacion;
			}
			set
			{
				if ((this._FechaCreacion != value))
				{
					this.OnFechaCreacionChanging(value);
					this.SendPropertyChanging();
					this._FechaCreacion = value;
					this.SendPropertyChanged("FechaCreacion");
					this.OnFechaCreacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioActualizacion", DbType="VarChar(20)")]
		public string UsuarioActualizacion
		{
			get
			{
				return this._UsuarioActualizacion;
			}
			set
			{
				if ((this._UsuarioActualizacion != value))
				{
					this.OnUsuarioActualizacionChanging(value);
					this.SendPropertyChanging();
					this._UsuarioActualizacion = value;
					this.SendPropertyChanged("UsuarioActualizacion");
					this.OnUsuarioActualizacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaActualizacion", DbType="Date")]
		public System.Nullable<System.DateTime> FechaActualizacion
		{
			get
			{
				return this._FechaActualizacion;
			}
			set
			{
				if ((this._FechaActualizacion != value))
				{
					this.OnFechaActualizacionChanging(value);
					this.SendPropertyChanging();
					this._FechaActualizacion = value;
					this.SendPropertyChanged("FechaActualizacion");
					this.OnFechaActualizacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Analisis_Muestra_analisis", Storage="_Muestra_analisis", ThisKey="IdAnalisis", OtherKey="IdAnalisis")]
		public EntitySet<Muestra_analisis> Muestra_analisis
		{
			get
			{
				return this._Muestra_analisis;
			}
			set
			{
				this._Muestra_analisis.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Muestra_analisis(Muestra_analisis entity)
		{
			this.SendPropertyChanging();
			entity.Analisis = this;
		}
		
		private void detach_Muestra_analisis(Muestra_analisis entity)
		{
			this.SendPropertyChanging();
			entity.Analisis = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Telefono")]
	public partial class Telefono : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdPersona;
		
		private string _Numero;
		
		private EntityRef<Persona> _Persona;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdPersonaChanging(int value);
    partial void OnIdPersonaChanged();
    partial void OnNumeroChanging(string value);
    partial void OnNumeroChanged();
    #endregion
		
		public Telefono()
		{
			this._Persona = default(EntityRef<Persona>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPersona", DbType="Int NOT NULL")]
		public int IdPersona
		{
			get
			{
				return this._IdPersona;
			}
			set
			{
				if ((this._IdPersona != value))
				{
					if (this._Persona.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdPersonaChanging(value);
					this.SendPropertyChanging();
					this._IdPersona = value;
					this.SendPropertyChanged("IdPersona");
					this.OnIdPersonaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Numero", DbType="VarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Numero
		{
			get
			{
				return this._Numero;
			}
			set
			{
				if ((this._Numero != value))
				{
					this.OnNumeroChanging(value);
					this.SendPropertyChanging();
					this._Numero = value;
					this.SendPropertyChanged("Numero");
					this.OnNumeroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Persona_Telefono", Storage="_Persona", ThisKey="IdPersona", OtherKey="ID_Persona", IsForeignKey=true)]
		public Persona Persona
		{
			get
			{
				return this._Persona.Entity;
			}
			set
			{
				Persona previousValue = this._Persona.Entity;
				if (((previousValue != value) 
							|| (this._Persona.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Persona.Entity = null;
						previousValue.Telefono.Remove(this);
					}
					this._Persona.Entity = value;
					if ((value != null))
					{
						value.Telefono.Add(this);
						this._IdPersona = value.ID_Persona;
					}
					else
					{
						this._IdPersona = default(int);
					}
					this.SendPropertyChanged("Persona");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Factura")]
	public partial class Factura : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdFactura;
		
		private System.DateTime _Fecha;
		
		private int _Costo;
		
		private int _IdCliente;
		
		private string _UsuarioCreacion;
		
		private System.DateTime _FechaCreacion;
		
		private string _UsuarioActualizacion;
		
		private System.Nullable<System.DateTime> _FechaActualizacion;
		
		private EntitySet<Muestra_analisis> _Muestra_analisis;
		
		private EntityRef<Persona> _Persona;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdFacturaChanging(int value);
    partial void OnIdFacturaChanged();
    partial void OnFechaChanging(System.DateTime value);
    partial void OnFechaChanged();
    partial void OnCostoChanging(int value);
    partial void OnCostoChanged();
    partial void OnIdClienteChanging(int value);
    partial void OnIdClienteChanged();
    partial void OnUsuarioCreacionChanging(string value);
    partial void OnUsuarioCreacionChanged();
    partial void OnFechaCreacionChanging(System.DateTime value);
    partial void OnFechaCreacionChanged();
    partial void OnUsuarioActualizacionChanging(string value);
    partial void OnUsuarioActualizacionChanged();
    partial void OnFechaActualizacionChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaActualizacionChanged();
    #endregion
		
		public Factura()
		{
			this._Muestra_analisis = new EntitySet<Muestra_analisis>(new Action<Muestra_analisis>(this.attach_Muestra_analisis), new Action<Muestra_analisis>(this.detach_Muestra_analisis));
			this._Persona = default(EntityRef<Persona>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdFactura", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdFactura
		{
			get
			{
				return this._IdFactura;
			}
			set
			{
				if ((this._IdFactura != value))
				{
					this.OnIdFacturaChanging(value);
					this.SendPropertyChanging();
					this._IdFactura = value;
					this.SendPropertyChanged("IdFactura");
					this.OnIdFacturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="Date NOT NULL")]
		public System.DateTime Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Costo", DbType="Int NOT NULL")]
		public int Costo
		{
			get
			{
				return this._Costo;
			}
			set
			{
				if ((this._Costo != value))
				{
					this.OnCostoChanging(value);
					this.SendPropertyChanging();
					this._Costo = value;
					this.SendPropertyChanged("Costo");
					this.OnCostoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCliente", DbType="Int NOT NULL")]
		public int IdCliente
		{
			get
			{
				return this._IdCliente;
			}
			set
			{
				if ((this._IdCliente != value))
				{
					if (this._Persona.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdClienteChanging(value);
					this.SendPropertyChanging();
					this._IdCliente = value;
					this.SendPropertyChanged("IdCliente");
					this.OnIdClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioCreacion", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string UsuarioCreacion
		{
			get
			{
				return this._UsuarioCreacion;
			}
			set
			{
				if ((this._UsuarioCreacion != value))
				{
					this.OnUsuarioCreacionChanging(value);
					this.SendPropertyChanging();
					this._UsuarioCreacion = value;
					this.SendPropertyChanged("UsuarioCreacion");
					this.OnUsuarioCreacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCreacion", DbType="Date NOT NULL")]
		public System.DateTime FechaCreacion
		{
			get
			{
				return this._FechaCreacion;
			}
			set
			{
				if ((this._FechaCreacion != value))
				{
					this.OnFechaCreacionChanging(value);
					this.SendPropertyChanging();
					this._FechaCreacion = value;
					this.SendPropertyChanged("FechaCreacion");
					this.OnFechaCreacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioActualizacion", DbType="VarChar(20)")]
		public string UsuarioActualizacion
		{
			get
			{
				return this._UsuarioActualizacion;
			}
			set
			{
				if ((this._UsuarioActualizacion != value))
				{
					this.OnUsuarioActualizacionChanging(value);
					this.SendPropertyChanging();
					this._UsuarioActualizacion = value;
					this.SendPropertyChanged("UsuarioActualizacion");
					this.OnUsuarioActualizacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaActualizacion", DbType="Date")]
		public System.Nullable<System.DateTime> FechaActualizacion
		{
			get
			{
				return this._FechaActualizacion;
			}
			set
			{
				if ((this._FechaActualizacion != value))
				{
					this.OnFechaActualizacionChanging(value);
					this.SendPropertyChanging();
					this._FechaActualizacion = value;
					this.SendPropertyChanged("FechaActualizacion");
					this.OnFechaActualizacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Factura_Muestra_analisis", Storage="_Muestra_analisis", ThisKey="IdFactura", OtherKey="IdFactura")]
		public EntitySet<Muestra_analisis> Muestra_analisis
		{
			get
			{
				return this._Muestra_analisis;
			}
			set
			{
				this._Muestra_analisis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Persona_Factura", Storage="_Persona", ThisKey="IdCliente", OtherKey="ID_Persona", IsForeignKey=true)]
		public Persona Persona
		{
			get
			{
				return this._Persona.Entity;
			}
			set
			{
				Persona previousValue = this._Persona.Entity;
				if (((previousValue != value) 
							|| (this._Persona.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Persona.Entity = null;
						previousValue.Factura.Remove(this);
					}
					this._Persona.Entity = value;
					if ((value != null))
					{
						value.Factura.Add(this);
						this._IdCliente = value.ID_Persona;
					}
					else
					{
						this._IdCliente = default(int);
					}
					this.SendPropertyChanged("Persona");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Muestra_analisis(Muestra_analisis entity)
		{
			this.SendPropertyChanging();
			entity.Factura = this;
		}
		
		private void detach_Muestra_analisis(Muestra_analisis entity)
		{
			this.SendPropertyChanging();
			entity.Factura = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Muestra")]
	public partial class Muestra : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Codigo;
		
		private string _Campo;
		
		private int _IdCliente;
		
		private string _Provincia;
		
		private string _Canton;
		
		private string _Distrito;
		
		private string _Direccion;
		
		private string _UsuarioCracion;
		
		private System.DateTime _FechaCreacion;
		
		private string _UsuarioActualizacion;
		
		private System.Nullable<System.DateTime> _FechaActualizacion;
		
		private EntitySet<Muestra_analisis> _Muestra_analisis;
		
		private EntityRef<Persona> _Persona;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoChanging(string value);
    partial void OnCodigoChanged();
    partial void OnCampoChanging(string value);
    partial void OnCampoChanged();
    partial void OnIdClienteChanging(int value);
    partial void OnIdClienteChanged();
    partial void OnProvinciaChanging(string value);
    partial void OnProvinciaChanged();
    partial void OnCantonChanging(string value);
    partial void OnCantonChanged();
    partial void OnDistritoChanging(string value);
    partial void OnDistritoChanged();
    partial void OnDireccionChanging(string value);
    partial void OnDireccionChanged();
    partial void OnUsuarioCracionChanging(string value);
    partial void OnUsuarioCracionChanged();
    partial void OnFechaCreacionChanging(System.DateTime value);
    partial void OnFechaCreacionChanged();
    partial void OnUsuarioActualizacionChanging(string value);
    partial void OnUsuarioActualizacionChanged();
    partial void OnFechaActualizacionChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaActualizacionChanged();
    #endregion
		
		public Muestra()
		{
			this._Muestra_analisis = new EntitySet<Muestra_analisis>(new Action<Muestra_analisis>(this.attach_Muestra_analisis), new Action<Muestra_analisis>(this.detach_Muestra_analisis));
			this._Persona = default(EntityRef<Persona>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this.OnCodigoChanging(value);
					this.SendPropertyChanging();
					this._Codigo = value;
					this.SendPropertyChanged("Codigo");
					this.OnCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Campo", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string Campo
		{
			get
			{
				return this._Campo;
			}
			set
			{
				if ((this._Campo != value))
				{
					this.OnCampoChanging(value);
					this.SendPropertyChanging();
					this._Campo = value;
					this.SendPropertyChanged("Campo");
					this.OnCampoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCliente", DbType="Int NOT NULL")]
		public int IdCliente
		{
			get
			{
				return this._IdCliente;
			}
			set
			{
				if ((this._IdCliente != value))
				{
					if (this._Persona.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdClienteChanging(value);
					this.SendPropertyChanging();
					this._IdCliente = value;
					this.SendPropertyChanged("IdCliente");
					this.OnIdClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Provincia", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Provincia
		{
			get
			{
				return this._Provincia;
			}
			set
			{
				if ((this._Provincia != value))
				{
					this.OnProvinciaChanging(value);
					this.SendPropertyChanging();
					this._Provincia = value;
					this.SendPropertyChanged("Provincia");
					this.OnProvinciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Canton", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Canton
		{
			get
			{
				return this._Canton;
			}
			set
			{
				if ((this._Canton != value))
				{
					this.OnCantonChanging(value);
					this.SendPropertyChanging();
					this._Canton = value;
					this.SendPropertyChanged("Canton");
					this.OnCantonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Distrito", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string Distrito
		{
			get
			{
				return this._Distrito;
			}
			set
			{
				if ((this._Distrito != value))
				{
					this.OnDistritoChanging(value);
					this.SendPropertyChanging();
					this._Distrito = value;
					this.SendPropertyChanged("Distrito");
					this.OnDistritoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this.OnDireccionChanging(value);
					this.SendPropertyChanging();
					this._Direccion = value;
					this.SendPropertyChanged("Direccion");
					this.OnDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioCracion", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string UsuarioCracion
		{
			get
			{
				return this._UsuarioCracion;
			}
			set
			{
				if ((this._UsuarioCracion != value))
				{
					this.OnUsuarioCracionChanging(value);
					this.SendPropertyChanging();
					this._UsuarioCracion = value;
					this.SendPropertyChanged("UsuarioCracion");
					this.OnUsuarioCracionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCreacion", DbType="Date NOT NULL")]
		public System.DateTime FechaCreacion
		{
			get
			{
				return this._FechaCreacion;
			}
			set
			{
				if ((this._FechaCreacion != value))
				{
					this.OnFechaCreacionChanging(value);
					this.SendPropertyChanging();
					this._FechaCreacion = value;
					this.SendPropertyChanged("FechaCreacion");
					this.OnFechaCreacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioActualizacion", DbType="VarChar(20)")]
		public string UsuarioActualizacion
		{
			get
			{
				return this._UsuarioActualizacion;
			}
			set
			{
				if ((this._UsuarioActualizacion != value))
				{
					this.OnUsuarioActualizacionChanging(value);
					this.SendPropertyChanging();
					this._UsuarioActualizacion = value;
					this.SendPropertyChanged("UsuarioActualizacion");
					this.OnUsuarioActualizacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaActualizacion", DbType="Date")]
		public System.Nullable<System.DateTime> FechaActualizacion
		{
			get
			{
				return this._FechaActualizacion;
			}
			set
			{
				if ((this._FechaActualizacion != value))
				{
					this.OnFechaActualizacionChanging(value);
					this.SendPropertyChanging();
					this._FechaActualizacion = value;
					this.SendPropertyChanged("FechaActualizacion");
					this.OnFechaActualizacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Muestra_Muestra_analisis", Storage="_Muestra_analisis", ThisKey="Codigo", OtherKey="Codigo")]
		public EntitySet<Muestra_analisis> Muestra_analisis
		{
			get
			{
				return this._Muestra_analisis;
			}
			set
			{
				this._Muestra_analisis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Persona_Muestra", Storage="_Persona", ThisKey="IdCliente", OtherKey="ID_Persona", IsForeignKey=true)]
		public Persona Persona
		{
			get
			{
				return this._Persona.Entity;
			}
			set
			{
				Persona previousValue = this._Persona.Entity;
				if (((previousValue != value) 
							|| (this._Persona.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Persona.Entity = null;
						previousValue.Muestra.Remove(this);
					}
					this._Persona.Entity = value;
					if ((value != null))
					{
						value.Muestra.Add(this);
						this._IdCliente = value.ID_Persona;
					}
					else
					{
						this._IdCliente = default(int);
					}
					this.SendPropertyChanged("Persona");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Muestra_analisis(Muestra_analisis entity)
		{
			this.SendPropertyChanging();
			entity.Muestra = this;
		}
		
		private void detach_Muestra_analisis(Muestra_analisis entity)
		{
			this.SendPropertyChanging();
			entity.Muestra = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Muestra_analisis")]
	public partial class Muestra_analisis : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdMuestraAnalisis;
		
		private string _Nombre;
		
		private int _Costo;
		
		private string _Codigo;
		
		private int _IdFactura;
		
		private int _IdAnalisis;
		
		private byte _Estado;
		
		private string _UsuarioCreacion;
		
		private System.DateTime _FechaCreacion;
		
		private string _UsuarioActualizacion;
		
		private System.Nullable<System.DateTime> _FechaActualizacion;
		
		private EntitySet<Resultado_analisis> _Resultado_analisis;
		
		private EntityRef<Analisis> _Analisis;
		
		private EntityRef<Factura> _Factura;
		
		private EntityRef<Muestra> _Muestra;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdMuestraAnalisisChanging(int value);
    partial void OnIdMuestraAnalisisChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnCostoChanging(int value);
    partial void OnCostoChanged();
    partial void OnCodigoChanging(string value);
    partial void OnCodigoChanged();
    partial void OnIdFacturaChanging(int value);
    partial void OnIdFacturaChanged();
    partial void OnIdAnalisisChanging(int value);
    partial void OnIdAnalisisChanged();
    partial void OnEstadoChanging(byte value);
    partial void OnEstadoChanged();
    partial void OnUsuarioCreacionChanging(string value);
    partial void OnUsuarioCreacionChanged();
    partial void OnFechaCreacionChanging(System.DateTime value);
    partial void OnFechaCreacionChanged();
    partial void OnUsuarioActualizacionChanging(string value);
    partial void OnUsuarioActualizacionChanged();
    partial void OnFechaActualizacionChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaActualizacionChanged();
    #endregion
		
		public Muestra_analisis()
		{
			this._Resultado_analisis = new EntitySet<Resultado_analisis>(new Action<Resultado_analisis>(this.attach_Resultado_analisis), new Action<Resultado_analisis>(this.detach_Resultado_analisis));
			this._Analisis = default(EntityRef<Analisis>);
			this._Factura = default(EntityRef<Factura>);
			this._Muestra = default(EntityRef<Muestra>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMuestraAnalisis", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdMuestraAnalisis
		{
			get
			{
				return this._IdMuestraAnalisis;
			}
			set
			{
				if ((this._IdMuestraAnalisis != value))
				{
					this.OnIdMuestraAnalisisChanging(value);
					this.SendPropertyChanging();
					this._IdMuestraAnalisis = value;
					this.SendPropertyChanged("IdMuestraAnalisis");
					this.OnIdMuestraAnalisisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Costo", DbType="Int NOT NULL")]
		public int Costo
		{
			get
			{
				return this._Costo;
			}
			set
			{
				if ((this._Costo != value))
				{
					this.OnCostoChanging(value);
					this.SendPropertyChanging();
					this._Costo = value;
					this.SendPropertyChanged("Costo");
					this.OnCostoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					if (this._Muestra.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodigoChanging(value);
					this.SendPropertyChanging();
					this._Codigo = value;
					this.SendPropertyChanged("Codigo");
					this.OnCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdFactura", DbType="Int NOT NULL")]
		public int IdFactura
		{
			get
			{
				return this._IdFactura;
			}
			set
			{
				if ((this._IdFactura != value))
				{
					if (this._Factura.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdFacturaChanging(value);
					this.SendPropertyChanging();
					this._IdFactura = value;
					this.SendPropertyChanged("IdFactura");
					this.OnIdFacturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAnalisis", DbType="Int NOT NULL")]
		public int IdAnalisis
		{
			get
			{
				return this._IdAnalisis;
			}
			set
			{
				if ((this._IdAnalisis != value))
				{
					if (this._Analisis.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdAnalisisChanging(value);
					this.SendPropertyChanging();
					this._IdAnalisis = value;
					this.SendPropertyChanged("IdAnalisis");
					this.OnIdAnalisisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="TinyInt NOT NULL")]
		public byte Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioCreacion", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string UsuarioCreacion
		{
			get
			{
				return this._UsuarioCreacion;
			}
			set
			{
				if ((this._UsuarioCreacion != value))
				{
					this.OnUsuarioCreacionChanging(value);
					this.SendPropertyChanging();
					this._UsuarioCreacion = value;
					this.SendPropertyChanged("UsuarioCreacion");
					this.OnUsuarioCreacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCreacion", DbType="Date NOT NULL")]
		public System.DateTime FechaCreacion
		{
			get
			{
				return this._FechaCreacion;
			}
			set
			{
				if ((this._FechaCreacion != value))
				{
					this.OnFechaCreacionChanging(value);
					this.SendPropertyChanging();
					this._FechaCreacion = value;
					this.SendPropertyChanged("FechaCreacion");
					this.OnFechaCreacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioActualizacion", DbType="VarChar(20)")]
		public string UsuarioActualizacion
		{
			get
			{
				return this._UsuarioActualizacion;
			}
			set
			{
				if ((this._UsuarioActualizacion != value))
				{
					this.OnUsuarioActualizacionChanging(value);
					this.SendPropertyChanging();
					this._UsuarioActualizacion = value;
					this.SendPropertyChanged("UsuarioActualizacion");
					this.OnUsuarioActualizacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaActualizacion", DbType="Date")]
		public System.Nullable<System.DateTime> FechaActualizacion
		{
			get
			{
				return this._FechaActualizacion;
			}
			set
			{
				if ((this._FechaActualizacion != value))
				{
					this.OnFechaActualizacionChanging(value);
					this.SendPropertyChanging();
					this._FechaActualizacion = value;
					this.SendPropertyChanged("FechaActualizacion");
					this.OnFechaActualizacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Muestra_analisis_Resultado_analisis", Storage="_Resultado_analisis", ThisKey="IdMuestraAnalisis", OtherKey="IdMuestraAnalisis")]
		public EntitySet<Resultado_analisis> Resultado_analisis
		{
			get
			{
				return this._Resultado_analisis;
			}
			set
			{
				this._Resultado_analisis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Analisis_Muestra_analisis", Storage="_Analisis", ThisKey="IdAnalisis", OtherKey="IdAnalisis", IsForeignKey=true)]
		public Analisis Analisis
		{
			get
			{
				return this._Analisis.Entity;
			}
			set
			{
				Analisis previousValue = this._Analisis.Entity;
				if (((previousValue != value) 
							|| (this._Analisis.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Analisis.Entity = null;
						previousValue.Muestra_analisis.Remove(this);
					}
					this._Analisis.Entity = value;
					if ((value != null))
					{
						value.Muestra_analisis.Add(this);
						this._IdAnalisis = value.IdAnalisis;
					}
					else
					{
						this._IdAnalisis = default(int);
					}
					this.SendPropertyChanged("Analisis");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Factura_Muestra_analisis", Storage="_Factura", ThisKey="IdFactura", OtherKey="IdFactura", IsForeignKey=true)]
		public Factura Factura
		{
			get
			{
				return this._Factura.Entity;
			}
			set
			{
				Factura previousValue = this._Factura.Entity;
				if (((previousValue != value) 
							|| (this._Factura.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Factura.Entity = null;
						previousValue.Muestra_analisis.Remove(this);
					}
					this._Factura.Entity = value;
					if ((value != null))
					{
						value.Muestra_analisis.Add(this);
						this._IdFactura = value.IdFactura;
					}
					else
					{
						this._IdFactura = default(int);
					}
					this.SendPropertyChanged("Factura");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Muestra_Muestra_analisis", Storage="_Muestra", ThisKey="Codigo", OtherKey="Codigo", IsForeignKey=true)]
		public Muestra Muestra
		{
			get
			{
				return this._Muestra.Entity;
			}
			set
			{
				Muestra previousValue = this._Muestra.Entity;
				if (((previousValue != value) 
							|| (this._Muestra.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Muestra.Entity = null;
						previousValue.Muestra_analisis.Remove(this);
					}
					this._Muestra.Entity = value;
					if ((value != null))
					{
						value.Muestra_analisis.Add(this);
						this._Codigo = value.Codigo;
					}
					else
					{
						this._Codigo = default(string);
					}
					this.SendPropertyChanged("Muestra");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Resultado_analisis(Resultado_analisis entity)
		{
			this.SendPropertyChanging();
			entity.Muestra_analisis = this;
		}
		
		private void detach_Resultado_analisis(Resultado_analisis entity)
		{
			this.SendPropertyChanging();
			entity.Muestra_analisis = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Persona")]
	public partial class Persona : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Persona;
		
		private string _Nombre;
		
		private string _Apellido1;
		
		private string _Apellido2;
		
		private string _Correo;
		
		private string _Clave;
		
		private System.Nullable<System.DateTime> _FechaCreacion;
		
		private string _UsuarioCreacion;
		
		private System.Nullable<System.DateTime> _FechaActualizacion;
		
		private string _UsuarioActualizacion;
		
		private byte _Estado;
		
		private byte _Tipo;
		
		private string _NombreUsuario;
		
		private EntitySet<Telefono> _Telefono;
		
		private EntitySet<Factura> _Factura;
		
		private EntitySet<Muestra> _Muestra;
		
		private EntitySet<Reporte> _Reporte;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_PersonaChanging(int value);
    partial void OnID_PersonaChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnApellido1Changing(string value);
    partial void OnApellido1Changed();
    partial void OnApellido2Changing(string value);
    partial void OnApellido2Changed();
    partial void OnCorreoChanging(string value);
    partial void OnCorreoChanged();
    partial void OnClaveChanging(string value);
    partial void OnClaveChanged();
    partial void OnFechaCreacionChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaCreacionChanged();
    partial void OnUsuarioCreacionChanging(string value);
    partial void OnUsuarioCreacionChanged();
    partial void OnFechaActualizacionChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaActualizacionChanged();
    partial void OnUsuarioActualizacionChanging(string value);
    partial void OnUsuarioActualizacionChanged();
    partial void OnEstadoChanging(byte value);
    partial void OnEstadoChanged();
    partial void OnTipoChanging(byte value);
    partial void OnTipoChanged();
    partial void OnNombreUsuarioChanging(string value);
    partial void OnNombreUsuarioChanged();
    #endregion
		
		public Persona()
		{
			this._Telefono = new EntitySet<Telefono>(new Action<Telefono>(this.attach_Telefono), new Action<Telefono>(this.detach_Telefono));
			this._Factura = new EntitySet<Factura>(new Action<Factura>(this.attach_Factura), new Action<Factura>(this.detach_Factura));
			this._Muestra = new EntitySet<Muestra>(new Action<Muestra>(this.attach_Muestra), new Action<Muestra>(this.detach_Muestra));
			this._Reporte = new EntitySet<Reporte>(new Action<Reporte>(this.attach_Reporte), new Action<Reporte>(this.detach_Reporte));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Persona", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_Persona
		{
			get
			{
				return this._ID_Persona;
			}
			set
			{
				if ((this._ID_Persona != value))
				{
					this.OnID_PersonaChanging(value);
					this.SendPropertyChanging();
					this._ID_Persona = value;
					this.SendPropertyChanged("ID_Persona");
					this.OnID_PersonaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido1", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string Apellido1
		{
			get
			{
				return this._Apellido1;
			}
			set
			{
				if ((this._Apellido1 != value))
				{
					this.OnApellido1Changing(value);
					this.SendPropertyChanging();
					this._Apellido1 = value;
					this.SendPropertyChanged("Apellido1");
					this.OnApellido1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido2", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string Apellido2
		{
			get
			{
				return this._Apellido2;
			}
			set
			{
				if ((this._Apellido2 != value))
				{
					this.OnApellido2Changing(value);
					this.SendPropertyChanging();
					this._Apellido2 = value;
					this.SendPropertyChanged("Apellido2");
					this.OnApellido2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string Correo
		{
			get
			{
				return this._Correo;
			}
			set
			{
				if ((this._Correo != value))
				{
					this.OnCorreoChanging(value);
					this.SendPropertyChanging();
					this._Correo = value;
					this.SendPropertyChanged("Correo");
					this.OnCorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Clave", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string Clave
		{
			get
			{
				return this._Clave;
			}
			set
			{
				if ((this._Clave != value))
				{
					this.OnClaveChanging(value);
					this.SendPropertyChanging();
					this._Clave = value;
					this.SendPropertyChanged("Clave");
					this.OnClaveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCreacion", DbType="Date")]
		public System.Nullable<System.DateTime> FechaCreacion
		{
			get
			{
				return this._FechaCreacion;
			}
			set
			{
				if ((this._FechaCreacion != value))
				{
					this.OnFechaCreacionChanging(value);
					this.SendPropertyChanging();
					this._FechaCreacion = value;
					this.SendPropertyChanged("FechaCreacion");
					this.OnFechaCreacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioCreacion", DbType="VarChar(25)")]
		public string UsuarioCreacion
		{
			get
			{
				return this._UsuarioCreacion;
			}
			set
			{
				if ((this._UsuarioCreacion != value))
				{
					this.OnUsuarioCreacionChanging(value);
					this.SendPropertyChanging();
					this._UsuarioCreacion = value;
					this.SendPropertyChanged("UsuarioCreacion");
					this.OnUsuarioCreacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaActualizacion", DbType="Date")]
		public System.Nullable<System.DateTime> FechaActualizacion
		{
			get
			{
				return this._FechaActualizacion;
			}
			set
			{
				if ((this._FechaActualizacion != value))
				{
					this.OnFechaActualizacionChanging(value);
					this.SendPropertyChanging();
					this._FechaActualizacion = value;
					this.SendPropertyChanged("FechaActualizacion");
					this.OnFechaActualizacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioActualizacion", DbType="VarChar(25)")]
		public string UsuarioActualizacion
		{
			get
			{
				return this._UsuarioActualizacion;
			}
			set
			{
				if ((this._UsuarioActualizacion != value))
				{
					this.OnUsuarioActualizacionChanging(value);
					this.SendPropertyChanging();
					this._UsuarioActualizacion = value;
					this.SendPropertyChanged("UsuarioActualizacion");
					this.OnUsuarioActualizacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="TinyInt NOT NULL")]
		public byte Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo", DbType="TinyInt NOT NULL")]
		public byte Tipo
		{
			get
			{
				return this._Tipo;
			}
			set
			{
				if ((this._Tipo != value))
				{
					this.OnTipoChanging(value);
					this.SendPropertyChanging();
					this._Tipo = value;
					this.SendPropertyChanged("Tipo");
					this.OnTipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreUsuario", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string NombreUsuario
		{
			get
			{
				return this._NombreUsuario;
			}
			set
			{
				if ((this._NombreUsuario != value))
				{
					this.OnNombreUsuarioChanging(value);
					this.SendPropertyChanging();
					this._NombreUsuario = value;
					this.SendPropertyChanged("NombreUsuario");
					this.OnNombreUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Persona_Telefono", Storage="_Telefono", ThisKey="ID_Persona", OtherKey="IdPersona")]
		public EntitySet<Telefono> Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				this._Telefono.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Persona_Factura", Storage="_Factura", ThisKey="ID_Persona", OtherKey="IdCliente")]
		public EntitySet<Factura> Factura
		{
			get
			{
				return this._Factura;
			}
			set
			{
				this._Factura.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Persona_Muestra", Storage="_Muestra", ThisKey="ID_Persona", OtherKey="IdCliente")]
		public EntitySet<Muestra> Muestra
		{
			get
			{
				return this._Muestra;
			}
			set
			{
				this._Muestra.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Persona_Reporte", Storage="_Reporte", ThisKey="ID_Persona", OtherKey="IdCliente")]
		public EntitySet<Reporte> Reporte
		{
			get
			{
				return this._Reporte;
			}
			set
			{
				this._Reporte.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Telefono(Telefono entity)
		{
			this.SendPropertyChanging();
			entity.Persona = this;
		}
		
		private void detach_Telefono(Telefono entity)
		{
			this.SendPropertyChanging();
			entity.Persona = null;
		}
		
		private void attach_Factura(Factura entity)
		{
			this.SendPropertyChanging();
			entity.Persona = this;
		}
		
		private void detach_Factura(Factura entity)
		{
			this.SendPropertyChanging();
			entity.Persona = null;
		}
		
		private void attach_Muestra(Muestra entity)
		{
			this.SendPropertyChanging();
			entity.Persona = this;
		}
		
		private void detach_Muestra(Muestra entity)
		{
			this.SendPropertyChanging();
			entity.Persona = null;
		}
		
		private void attach_Reporte(Reporte entity)
		{
			this.SendPropertyChanging();
			entity.Persona = this;
		}
		
		private void detach_Reporte(Reporte entity)
		{
			this.SendPropertyChanging();
			entity.Persona = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Reporte")]
	public partial class Reporte : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdReporte;
		
		private System.Nullable<System.DateTime> _Fecha;
		
		private string _Metodologia;
		
		private string _Observaciones;
		
		private int _IdUsuario;
		
		private int _IdCliente;
		
		private EntitySet<Resultado_analisis> _Resultado_analisis;
		
		private EntityRef<Persona> _Persona;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdReporteChanging(int value);
    partial void OnIdReporteChanged();
    partial void OnFechaChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaChanged();
    partial void OnMetodologiaChanging(string value);
    partial void OnMetodologiaChanged();
    partial void OnObservacionesChanging(string value);
    partial void OnObservacionesChanged();
    partial void OnIdUsuarioChanging(int value);
    partial void OnIdUsuarioChanged();
    partial void OnIdClienteChanging(int value);
    partial void OnIdClienteChanged();
    #endregion
		
		public Reporte()
		{
			this._Resultado_analisis = new EntitySet<Resultado_analisis>(new Action<Resultado_analisis>(this.attach_Resultado_analisis), new Action<Resultado_analisis>(this.detach_Resultado_analisis));
			this._Persona = default(EntityRef<Persona>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdReporte", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdReporte
		{
			get
			{
				return this._IdReporte;
			}
			set
			{
				if ((this._IdReporte != value))
				{
					this.OnIdReporteChanging(value);
					this.SendPropertyChanging();
					this._IdReporte = value;
					this.SendPropertyChanged("IdReporte");
					this.OnIdReporteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="Date")]
		public System.Nullable<System.DateTime> Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Metodologia", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string Metodologia
		{
			get
			{
				return this._Metodologia;
			}
			set
			{
				if ((this._Metodologia != value))
				{
					this.OnMetodologiaChanging(value);
					this.SendPropertyChanging();
					this._Metodologia = value;
					this.SendPropertyChanged("Metodologia");
					this.OnMetodologiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Observaciones", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string Observaciones
		{
			get
			{
				return this._Observaciones;
			}
			set
			{
				if ((this._Observaciones != value))
				{
					this.OnObservacionesChanging(value);
					this.SendPropertyChanging();
					this._Observaciones = value;
					this.SendPropertyChanged("Observaciones");
					this.OnObservacionesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="Int NOT NULL")]
		public int IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					this.OnIdUsuarioChanging(value);
					this.SendPropertyChanging();
					this._IdUsuario = value;
					this.SendPropertyChanged("IdUsuario");
					this.OnIdUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCliente", DbType="Int NOT NULL")]
		public int IdCliente
		{
			get
			{
				return this._IdCliente;
			}
			set
			{
				if ((this._IdCliente != value))
				{
					if (this._Persona.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdClienteChanging(value);
					this.SendPropertyChanging();
					this._IdCliente = value;
					this.SendPropertyChanged("IdCliente");
					this.OnIdClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Reporte_Resultado_analisis", Storage="_Resultado_analisis", ThisKey="IdReporte", OtherKey="IdReporte")]
		public EntitySet<Resultado_analisis> Resultado_analisis
		{
			get
			{
				return this._Resultado_analisis;
			}
			set
			{
				this._Resultado_analisis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Persona_Reporte", Storage="_Persona", ThisKey="IdCliente", OtherKey="ID_Persona", IsForeignKey=true)]
		public Persona Persona
		{
			get
			{
				return this._Persona.Entity;
			}
			set
			{
				Persona previousValue = this._Persona.Entity;
				if (((previousValue != value) 
							|| (this._Persona.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Persona.Entity = null;
						previousValue.Reporte.Remove(this);
					}
					this._Persona.Entity = value;
					if ((value != null))
					{
						value.Reporte.Add(this);
						this._IdCliente = value.ID_Persona;
					}
					else
					{
						this._IdCliente = default(int);
					}
					this.SendPropertyChanged("Persona");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Resultado_analisis(Resultado_analisis entity)
		{
			this.SendPropertyChanging();
			entity.Reporte = this;
		}
		
		private void detach_Resultado_analisis(Resultado_analisis entity)
		{
			this.SendPropertyChanging();
			entity.Reporte = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Resultado_analisis")]
	public partial class Resultado_analisis : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdResultadoAnalisis;
		
		private int _IdMuestraAnalisis;
		
		private int _IdReporte;
		
		private byte _Estado;
		
		private int _UsuarioCreacion;
		
		private System.DateTime _FechaCreacion;
		
		private System.Nullable<int> _UsuarioActualizacion;
		
		private System.Nullable<System.DateTime> _FechaActualizacion;
		
		private EntitySet<Resultado_elemento> _Resultado_elemento;
		
		private EntityRef<Muestra_analisis> _Muestra_analisis;
		
		private EntityRef<Reporte> _Reporte;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdResultadoAnalisisChanging(int value);
    partial void OnIdResultadoAnalisisChanged();
    partial void OnIdMuestraAnalisisChanging(int value);
    partial void OnIdMuestraAnalisisChanged();
    partial void OnIdReporteChanging(int value);
    partial void OnIdReporteChanged();
    partial void OnEstadoChanging(byte value);
    partial void OnEstadoChanged();
    partial void OnUsuarioCreacionChanging(int value);
    partial void OnUsuarioCreacionChanged();
    partial void OnFechaCreacionChanging(System.DateTime value);
    partial void OnFechaCreacionChanged();
    partial void OnUsuarioActualizacionChanging(System.Nullable<int> value);
    partial void OnUsuarioActualizacionChanged();
    partial void OnFechaActualizacionChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaActualizacionChanged();
    #endregion
		
		public Resultado_analisis()
		{
			this._Resultado_elemento = new EntitySet<Resultado_elemento>(new Action<Resultado_elemento>(this.attach_Resultado_elemento), new Action<Resultado_elemento>(this.detach_Resultado_elemento));
			this._Muestra_analisis = default(EntityRef<Muestra_analisis>);
			this._Reporte = default(EntityRef<Reporte>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdResultadoAnalisis", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdResultadoAnalisis
		{
			get
			{
				return this._IdResultadoAnalisis;
			}
			set
			{
				if ((this._IdResultadoAnalisis != value))
				{
					this.OnIdResultadoAnalisisChanging(value);
					this.SendPropertyChanging();
					this._IdResultadoAnalisis = value;
					this.SendPropertyChanged("IdResultadoAnalisis");
					this.OnIdResultadoAnalisisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMuestraAnalisis", DbType="Int NOT NULL")]
		public int IdMuestraAnalisis
		{
			get
			{
				return this._IdMuestraAnalisis;
			}
			set
			{
				if ((this._IdMuestraAnalisis != value))
				{
					if (this._Muestra_analisis.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdMuestraAnalisisChanging(value);
					this.SendPropertyChanging();
					this._IdMuestraAnalisis = value;
					this.SendPropertyChanged("IdMuestraAnalisis");
					this.OnIdMuestraAnalisisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdReporte", DbType="Int NOT NULL")]
		public int IdReporte
		{
			get
			{
				return this._IdReporte;
			}
			set
			{
				if ((this._IdReporte != value))
				{
					if (this._Reporte.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdReporteChanging(value);
					this.SendPropertyChanging();
					this._IdReporte = value;
					this.SendPropertyChanged("IdReporte");
					this.OnIdReporteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="TinyInt NOT NULL")]
		public byte Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioCreacion", DbType="Int NOT NULL")]
		public int UsuarioCreacion
		{
			get
			{
				return this._UsuarioCreacion;
			}
			set
			{
				if ((this._UsuarioCreacion != value))
				{
					this.OnUsuarioCreacionChanging(value);
					this.SendPropertyChanging();
					this._UsuarioCreacion = value;
					this.SendPropertyChanged("UsuarioCreacion");
					this.OnUsuarioCreacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCreacion", DbType="Date NOT NULL")]
		public System.DateTime FechaCreacion
		{
			get
			{
				return this._FechaCreacion;
			}
			set
			{
				if ((this._FechaCreacion != value))
				{
					this.OnFechaCreacionChanging(value);
					this.SendPropertyChanging();
					this._FechaCreacion = value;
					this.SendPropertyChanged("FechaCreacion");
					this.OnFechaCreacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioActualizacion", DbType="Int")]
		public System.Nullable<int> UsuarioActualizacion
		{
			get
			{
				return this._UsuarioActualizacion;
			}
			set
			{
				if ((this._UsuarioActualizacion != value))
				{
					this.OnUsuarioActualizacionChanging(value);
					this.SendPropertyChanging();
					this._UsuarioActualizacion = value;
					this.SendPropertyChanged("UsuarioActualizacion");
					this.OnUsuarioActualizacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaActualizacion", DbType="Date")]
		public System.Nullable<System.DateTime> FechaActualizacion
		{
			get
			{
				return this._FechaActualizacion;
			}
			set
			{
				if ((this._FechaActualizacion != value))
				{
					this.OnFechaActualizacionChanging(value);
					this.SendPropertyChanging();
					this._FechaActualizacion = value;
					this.SendPropertyChanged("FechaActualizacion");
					this.OnFechaActualizacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Resultado_analisis_Resultado_elemento", Storage="_Resultado_elemento", ThisKey="IdResultadoAnalisis", OtherKey="IdResultadoAnalisis")]
		public EntitySet<Resultado_elemento> Resultado_elemento
		{
			get
			{
				return this._Resultado_elemento;
			}
			set
			{
				this._Resultado_elemento.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Muestra_analisis_Resultado_analisis", Storage="_Muestra_analisis", ThisKey="IdMuestraAnalisis", OtherKey="IdMuestraAnalisis", IsForeignKey=true)]
		public Muestra_analisis Muestra_analisis
		{
			get
			{
				return this._Muestra_analisis.Entity;
			}
			set
			{
				Muestra_analisis previousValue = this._Muestra_analisis.Entity;
				if (((previousValue != value) 
							|| (this._Muestra_analisis.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Muestra_analisis.Entity = null;
						previousValue.Resultado_analisis.Remove(this);
					}
					this._Muestra_analisis.Entity = value;
					if ((value != null))
					{
						value.Resultado_analisis.Add(this);
						this._IdMuestraAnalisis = value.IdMuestraAnalisis;
					}
					else
					{
						this._IdMuestraAnalisis = default(int);
					}
					this.SendPropertyChanged("Muestra_analisis");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Reporte_Resultado_analisis", Storage="_Reporte", ThisKey="IdReporte", OtherKey="IdReporte", IsForeignKey=true)]
		public Reporte Reporte
		{
			get
			{
				return this._Reporte.Entity;
			}
			set
			{
				Reporte previousValue = this._Reporte.Entity;
				if (((previousValue != value) 
							|| (this._Reporte.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Reporte.Entity = null;
						previousValue.Resultado_analisis.Remove(this);
					}
					this._Reporte.Entity = value;
					if ((value != null))
					{
						value.Resultado_analisis.Add(this);
						this._IdReporte = value.IdReporte;
					}
					else
					{
						this._IdReporte = default(int);
					}
					this.SendPropertyChanged("Reporte");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Resultado_elemento(Resultado_elemento entity)
		{
			this.SendPropertyChanging();
			entity.Resultado_analisis = this;
		}
		
		private void detach_Resultado_elemento(Resultado_elemento entity)
		{
			this.SendPropertyChanging();
			entity.Resultado_analisis = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Resultado_elemento")]
	public partial class Resultado_elemento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdResultadoElemento;
		
		private string _Nombre;
		
		private string _Resultado;
		
		private int _IdResultadoAnalisis;
		
		private string _UsuarioCreacion;
		
		private System.DateTime _FechaCracion;
		
		private string _UsuarioModificacion;
		
		private System.Nullable<System.DateTime> _FechaModificacion;
		
		private EntityRef<Resultado_analisis> _Resultado_analisis;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdResultadoElementoChanging(int value);
    partial void OnIdResultadoElementoChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnResultadoChanging(string value);
    partial void OnResultadoChanged();
    partial void OnIdResultadoAnalisisChanging(int value);
    partial void OnIdResultadoAnalisisChanged();
    partial void OnUsuarioCreacionChanging(string value);
    partial void OnUsuarioCreacionChanged();
    partial void OnFechaCracionChanging(System.DateTime value);
    partial void OnFechaCracionChanged();
    partial void OnUsuarioModificacionChanging(string value);
    partial void OnUsuarioModificacionChanged();
    partial void OnFechaModificacionChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaModificacionChanged();
    #endregion
		
		public Resultado_elemento()
		{
			this._Resultado_analisis = default(EntityRef<Resultado_analisis>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdResultadoElemento", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdResultadoElemento
		{
			get
			{
				return this._IdResultadoElemento;
			}
			set
			{
				if ((this._IdResultadoElemento != value))
				{
					this.OnIdResultadoElementoChanging(value);
					this.SendPropertyChanging();
					this._IdResultadoElemento = value;
					this.SendPropertyChanged("IdResultadoElemento");
					this.OnIdResultadoElementoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Resultado", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Resultado
		{
			get
			{
				return this._Resultado;
			}
			set
			{
				if ((this._Resultado != value))
				{
					this.OnResultadoChanging(value);
					this.SendPropertyChanging();
					this._Resultado = value;
					this.SendPropertyChanged("Resultado");
					this.OnResultadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdResultadoAnalisis", DbType="Int NOT NULL")]
		public int IdResultadoAnalisis
		{
			get
			{
				return this._IdResultadoAnalisis;
			}
			set
			{
				if ((this._IdResultadoAnalisis != value))
				{
					if (this._Resultado_analisis.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdResultadoAnalisisChanging(value);
					this.SendPropertyChanging();
					this._IdResultadoAnalisis = value;
					this.SendPropertyChanged("IdResultadoAnalisis");
					this.OnIdResultadoAnalisisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioCreacion", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string UsuarioCreacion
		{
			get
			{
				return this._UsuarioCreacion;
			}
			set
			{
				if ((this._UsuarioCreacion != value))
				{
					this.OnUsuarioCreacionChanging(value);
					this.SendPropertyChanging();
					this._UsuarioCreacion = value;
					this.SendPropertyChanged("UsuarioCreacion");
					this.OnUsuarioCreacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCracion", DbType="Date NOT NULL")]
		public System.DateTime FechaCracion
		{
			get
			{
				return this._FechaCracion;
			}
			set
			{
				if ((this._FechaCracion != value))
				{
					this.OnFechaCracionChanging(value);
					this.SendPropertyChanging();
					this._FechaCracion = value;
					this.SendPropertyChanged("FechaCracion");
					this.OnFechaCracionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioModificacion", DbType="VarChar(20)")]
		public string UsuarioModificacion
		{
			get
			{
				return this._UsuarioModificacion;
			}
			set
			{
				if ((this._UsuarioModificacion != value))
				{
					this.OnUsuarioModificacionChanging(value);
					this.SendPropertyChanging();
					this._UsuarioModificacion = value;
					this.SendPropertyChanged("UsuarioModificacion");
					this.OnUsuarioModificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModificacion", DbType="Date")]
		public System.Nullable<System.DateTime> FechaModificacion
		{
			get
			{
				return this._FechaModificacion;
			}
			set
			{
				if ((this._FechaModificacion != value))
				{
					this.OnFechaModificacionChanging(value);
					this.SendPropertyChanging();
					this._FechaModificacion = value;
					this.SendPropertyChanged("FechaModificacion");
					this.OnFechaModificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Resultado_analisis_Resultado_elemento", Storage="_Resultado_analisis", ThisKey="IdResultadoAnalisis", OtherKey="IdResultadoAnalisis", IsForeignKey=true)]
		public Resultado_analisis Resultado_analisis
		{
			get
			{
				return this._Resultado_analisis.Entity;
			}
			set
			{
				Resultado_analisis previousValue = this._Resultado_analisis.Entity;
				if (((previousValue != value) 
							|| (this._Resultado_analisis.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Resultado_analisis.Entity = null;
						previousValue.Resultado_elemento.Remove(this);
					}
					this._Resultado_analisis.Entity = value;
					if ((value != null))
					{
						value.Resultado_elemento.Add(this);
						this._IdResultadoAnalisis = value.IdResultadoAnalisis;
					}
					else
					{
						this._IdResultadoAnalisis = default(int);
					}
					this.SendPropertyChanged("Resultado_analisis");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
