//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAAG
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dato
    {
        public Dato()
        {
            this.Analisis_Dato = new HashSet<Analisis_Dato>();
            this.Resultado_Dato = new HashSet<Resultado_Dato>();
        }
    
        public int IdDato { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<Analisis_Dato> Analisis_Dato { get; set; }
        public virtual ICollection<Resultado_Dato> Resultado_Dato { get; set; }
    }
}
