//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAAG
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dato
    {
        public Dato()
        {
            this.Resultado_Dato = new HashSet<Resultado_Dato>();
        }
    
        public int IdDato { get; set; }
        public string Nombre { get; set; }
        public string unidadMedida { get; set; }
    
        public virtual ICollection<Resultado_Dato> Resultado_Dato { get; set; }
    }
}
