//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAAG
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distrito
    {
        public int ID_Distrito { get; set; }
        public int ID_Canton { get; set; }
        public string nombre { get; set; }
    
        public virtual Canton Canton { get; set; }
    }
}
