//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAAG
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distrito
    {
        public int ID_Distrito { get; set; }
        public int numeroDistrito { get; set; }
        public int numeroCanton { get; set; }
        public int numeroProvincia { get; set; }
        public string nombre { get; set; }
    
        public virtual Canton Canton { get; set; }
    }
}
