//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAAG
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public Factura()
        {
            this.Muestra_Analisis = new HashSet<Muestra_Analisis>();
        }
    
        public int IdFactura { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Costo { get; set; }
        public int IdPersona { get; set; }
    
        public virtual Persona Persona { get; set; }
        public virtual ICollection<Muestra_Analisis> Muestra_Analisis { get; set; }
    }
}
