//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAAG
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public Factura()
        {
            this.Muestra_analisis = new HashSet<Muestra_analisis>();
        }
    
        public int IdFactura { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Costo { get; set; }
        public int IdCliente { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioActualizacion { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
    
        public virtual Persona Persona { get; set; }
        public virtual ICollection<Muestra_analisis> Muestra_analisis { get; set; }
    }
}
