//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAAG
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public Factura()
        {
            this.Muestra_Analisis = new HashSet<Muestra_Analisis>();
        }
    
        public int IdFactura { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Costo { get; set; }
        public int IdPersona { get; set; }
    
        public virtual Persona Persona { get; set; }
        public virtual ICollection<Muestra_Analisis> Muestra_Analisis { get; set; }
    }
}
