//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAAG
{
    using System;
    using System.Collections.Generic;
    
    public partial class Muestra_Analisis
    {
        public Muestra_Analisis()
        {
            this.Resultado_Analisis = new HashSet<Resultado_Analisis>();
        }
    
        public int IdMuestraAnalisis { get; set; }
        public string Nombre { get; set; }
        public int Costo { get; set; }
        public string Codigo { get; set; }
        public int IdFactura { get; set; }
        public int IdAnalisis { get; set; }
        public byte Estado { get; set; }
    
        public virtual Analisis Analisis { get; set; }
        public virtual Factura Factura { get; set; }
        public virtual Muestra Muestra { get; set; }
        public virtual ICollection<Resultado_Analisis> Resultado_Analisis { get; set; }
    }
}
