//------------------------------------------------------------------------------
// <auto-generated>
<<<<<<< HEAD
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
=======
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
>>>>>>> master
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAAG
{
    using System;
    using System.Collections.Generic;
    
    public partial class Muestra_Analisis
    {
        public Muestra_Analisis()
        {
            this.Resultado_Analisis = new HashSet<Resultado_Analisis>();
        }
    
        public int IdMuestraAnalisis { get; set; }
        public string Nombre { get; set; }
        public decimal Costo { get; set; }
        public string Codigo { get; set; }
        public int IdFactura { get; set; }
        public int IdAnalisis { get; set; }
        public byte Estado { get; set; }
    
        public virtual Analisis Analisis { get; set; }
        public virtual Factura Factura { get; set; }
        public virtual Muestra Muestra { get; set; }
        public virtual ICollection<Resultado_Analisis> Resultado_Analisis { get; set; }
    }
}
