//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAAG
{
    using System;
    using System.Collections.Generic;
    
    public partial class Muestra_analisis
    {
        public Muestra_analisis()
        {
            this.Resultado_analisis = new HashSet<Resultado_analisis>();
        }
    
        public int IdMuestraAnalisis { get; set; }
        public string Nombre { get; set; }
        public int Costo { get; set; }
        public string Codigo { get; set; }
        public int IdFactura { get; set; }
        public int IdAnalisis { get; set; }
        public byte Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioActualizacion { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
    
        public virtual Analisis Analisis { get; set; }
        public virtual Factura Factura { get; set; }
        public virtual Muestra Muestra { get; set; }
        public virtual ICollection<Resultado_analisis> Resultado_analisis { get; set; }
    }
}
