//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAAG
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provincia
    {
        public Provincia()
        {
            this.Canton = new HashSet<Canton>();
            this.Muestra = new HashSet<Muestra>();
        }
    
        public int ID_Provincia { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<Canton> Canton { get; set; }
        public virtual ICollection<Muestra> Muestra { get; set; }
    }
}
