//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAAG
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provincia
    {
        public Provincia()
        {
            this.Muestra = new HashSet<Muestra>();
            this.Canton = new HashSet<Canton>();
        }
    
        public int numeroProvincia { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<Muestra> Muestra { get; set; }
        public virtual ICollection<Canton> Canton { get; set; }
    }
}
