//------------------------------------------------------------------------------
// <auto-generated>
<<<<<<< HEAD
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
=======
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
>>>>>>> master
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAAG
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reporte
    {
        public int IdReporte { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Metodologia { get; set; }
        public string Observaciones { get; set; }
        public int IdUsuario { get; set; }
        public int IdCliente { get; set; }
    
        public virtual Persona Persona { get; set; }
    }
}
