//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAAG
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resultado_Dato
    {
        public int IdResultadoDato { get; set; }
        public int IdDato { get; set; }
        public string Resultado { get; set; }
        public int IdResultadoAnalisis { get; set; }
    
        public virtual Dato Dato { get; set; }
        public virtual Resultado_Analisis Resultado_Analisis { get; set; }
    }
}
