//------------------------------------------------------------------------------
// <auto-generated>
<<<<<<< HEAD
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
=======
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
>>>>>>> master
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAAG
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resultado_Analisis
    {
        public Resultado_Analisis()
        {
            this.Resultado_Dato = new HashSet<Resultado_Dato>();
        }
    
        public int IdResultadoAnalisis { get; set; }
        public int IdMuestraAnalisis { get; set; }
        public int IdReporte { get; set; }
        public byte Estado { get; set; }
    
        public virtual Muestra_Analisis Muestra_Analisis { get; set; }
        public virtual ICollection<Resultado_Dato> Resultado_Dato { get; set; }
    }
}
