//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAAG
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resultado_Analisis
    {
        public Resultado_Analisis()
        {
            this.Resultado_Dato = new HashSet<Resultado_Dato>();
        }
    
        public int IdResultadoAnalisis { get; set; }
        public int IdMuestraAnalisis { get; set; }
        public int IdReporte { get; set; }
        public byte Estado { get; set; }
    
        public virtual Muestra_Analisis Muestra_Analisis { get; set; }
        public virtual Reporte Reporte { get; set; }
        public virtual ICollection<Resultado_Dato> Resultado_Dato { get; set; }
    }
}
