//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAAG
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resultado_analisis
    {
        public Resultado_analisis()
        {
            this.Resultado_elemento = new HashSet<Resultado_elemento>();
        }
    
        public int IdResultadoAnalisis { get; set; }
        public int IdMuestraAnalisis { get; set; }
        public int IdReporte { get; set; }
        public byte Estado { get; set; }
        public int UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<int> UsuarioActualizacion { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
    
        public virtual Muestra_analisis Muestra_analisis { get; set; }
        public virtual Reporte Reporte { get; set; }
        public virtual ICollection<Resultado_elemento> Resultado_elemento { get; set; }
    }
}
