//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAAG
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resultado_elemento
    {
        public int IdResultadoElemento { get; set; }
        public string Nombre { get; set; }
        public string Resultado { get; set; }
        public int IdResultadoAnalisis { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCracion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual Resultado_analisis Resultado_analisis { get; set; }
    }
}
