//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAAG
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resultado_Dato
    {
        public int IdResultadoDato { get; set; }
        public int IdDato { get; set; }
        public string Resultado { get; set; }
        public int IdResultadoAnalisis { get; set; }
    
        public virtual Dato Dato { get; set; }
        public virtual Resultado_Analisis Resultado_Analisis { get; set; }
    }
}
